sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 666666

  aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      bucketName: javaweb-com
      region: cn-beijing

  redis:
    host: localhost
    port: 6379
    password: 666666
    database: 10

  wechat:
    appid: wx4ebc60fa6cf98304
    secret: 77b0105f33633381cd211a897816d5cf
